In [5]:
import tensorflow as tf

# model.ckpt.meta contains the TensorFlow graph
save_file = 'model.ckpt'

# two tensor variable
weights = tf.Variable(tf.truncated_normal([2,3]), name="w1")
bias = tf.Variable(tf.truncated_normal([3]), name="b1")

# class used to save/restore Tensor Variables
saver = tf.train.Saver()

In [6]:
with tf.Session() as sess:
    # initialize all variables
    sess.run(tf.global_variables_initializer())
    
    print('weights: ')
    print(sess.run(weights))
    print('biases: ')
    print(sess.run(bias))
    
    # save the model
    save_path = saver.save(sess, save_file)
    print("Model saved in file: %s" % save_path)
    
    

weights: 
[[-0.08884048  1.32973289  1.14151418]
 [ 0.20099142  0.03992639 -0.45728549]]
biases: 
[ 1.0061264  -1.36702108 -1.16653168]
Model saved in file: model.ckpt
