In [1]:
import tensorflow as tf

# model.ckpt.meta contains the TensorFlow graph
save_file = '/home/anuj/research/sdc/udacity-selfdrivingcar/term-1/model.ckpt'

# two tensor variable
weights = tf.Variable(tf.truncated_normal([2,3]), name="w1")
bias = tf.Variable(tf.truncated_normal([3]), name="b1")

# class used to save/restore Tensor Variables
saver = tf.train.Saver()

In [2]:
with tf.Session() as sess:
    # initialize all variables
    sess.run(tf.global_variables_initializer())
    
    print('weights: ')
    print(sess.run(weights))
    print('biases: ')
    print(sess.run(bias))
    
    # save the model
    save_path = saver.save(sess, save_file)
    print("Model saved in file: %s" % save_path)
    
    

weights: 
[[-1.3580122   1.47015178 -0.97568232]
 [-0.59438705 -0.68100506 -1.42766857]]
biases: 
[-0.90178674  0.07336103  1.02497411]
Model saved in file: /home/anuj/research/sdc/udacity-selfdrivingcar/term-1/model.ckpt
