## python, cv2 functions

In [4]:
import matplotlib.image as mpimg
import matplotlib.pyplot as plt
import numpy as np
import cv2

In [5]:
image = mpimg.imread('ford-gt.jpg')

In [13]:
a = np.arange(15).reshape(3,5)

In [14]:
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [23]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [15]:
a.shape

(3, 5)

In [16]:
a.ndim

2

In [18]:
a.dtype.name

'int32'

In [19]:
a.itemsize

4

In [20]:
a.size

15

In [21]:
b = np.array([6,7,8])

In [22]:
b

array([6, 7, 8])

In [24]:
type(a)

numpy.ndarray

In [25]:
type(b)

numpy.ndarray

In [26]:
a = np.array([1,2,3,5])

In [27]:
a

array([1, 2, 3, 5])

In [58]:
a = np.array([[1,2],[1,4]])

In [59]:
a

array([[1, 2],
       [1, 4]])

In [60]:
b = np.array([[1,2],[4,2]])
b

array([[1, 2],
       [4, 2]])

In [62]:
np.dot(a,b)

array([[ 9,  6],
       [17, 10]])

In [51]:
a**10

array([[       1,     1024],
       [       1,  1048576],
       [60466176,     1024]], dtype=int32)

In [46]:
np.zeros((2,3,5,4))

array([[[[ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.]],

        [[ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.]],

        [[ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.]]],


       [[[ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.]],

        [[ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.]],

        [[ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.]]]])

In [33]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [35]:
np.arange(0,2,0.3)

array([ 0. ,  0.3,  0.6,  0.9,  1.2,  1.5,  1.8])

In [40]:
np.arange(0,2,0.2)

array([ 0. ,  0.2,  0.4,  0.6,  0.8,  1. ,  1.2,  1.4,  1.6,  1.8])